export const sampleProductResponse = {
  "id": 174,
  "name": "1L Le Parfait Jar",
  "type": "physical",
  "sku": "",
  "description": "<p><span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi vel metus ac est egestas porta sed quis erat. Integer id nulla massa. Proin vitae enim nisi. Praesent non dignissim nulla. Nulla mattis id massa ac pharetra. Mauris et nisi in dolor aliquam sodales. Aliquam dui nisl, dictum quis leo sit amet, rutrum volutpat metus. Curabitur libero nunc, interdum ac libero non, tristique porttitor metus. Ut non dignissim lorem, in vestibulum leo. Vivamus sodales quis turpis eget.</span></p>",
  "weight": 1,
  "width": 0,
  "depth": 0,
  "height": 0,
  "price": 7.95,
  "cost_price": 0,
  "retail_price": 10,
  "sale_price": 0,
  "map_price": 0,
  "tax_class_id": 0,
  "product_tax_code": "",
  "calculated_price": 7.95,
  "categories": [
    23,
    21
  ],
  "brand_id": 36,
  "option_set_id": 55,
  "option_set_display": "right",
  "inventory_level": 0,
  "inventory_warning_level": 0,
  "inventory_tracking": "none",
  "reviews_rating_sum": 0,
  "reviews_count": 0,
  "total_sold": 7,
  "fixed_cost_shipping_price": 0,
  "is_free_shipping": false,
  "is_visible": true,
  "is_featured": false,
  "related_products": [
    -1
  ],
  "warranty": "",
  "bin_picking_number": "",
  "layout_file": "product.html",
  "upc": "",
  "mpn": "",
  "gtin": "",
  "search_keywords": "jar, glass",
  "availability": "available",
  "availability_description": "",
  "gift_wrapping_options_type": "any",
  "gift_wrapping_options_list": [],
  "sort_order": 0,
  "condition": "New",
  "is_condition_shown": false,
  "order_quantity_minimum": 0,
  "order_quantity_maximum": 0,
  "page_title": "",
  "meta_keywords": [],
  "meta_description": "",
  "date_created": "2018-08-15T14:48:46+00:00",
  "date_modified": "2018-09-05T20:42:07+00:00",
  "view_count": 10,
  "preorder_release_date": "2018-09-05T20:42:07+00:00",
  "preorder_message": "",
  "is_preorder_only": false,
  "is_price_hidden": false,
  "price_hidden_label": "",
  "custom_url": {
    "url": "/all/1l-le-parfait-jar/",
    "is_customized": true
  },
  "base_variant_id": 345,
  "open_graph_type": "product",
  "open_graph_title": "",
  "open_graph_description": "",
  "open_graph_use_meta_description": true,
  "open_graph_use_product_name": true,
  "open_graph_use_image": true,
  "variants": [
    {
      "id": 345,
      "product_id": 174,
      "sku": "",
      "sku_id": {},
      "price": 7.95,
      "calculated_price": 7.95,
      "sale_price": 0,
      "retail_price": 10,
      "map_price": 0,
      "weight": 1,
      "width": 0,
      "height": 0,
      "depth": 0,
      "is_free_shipping": false,
      "fixed_cost_shipping_price": 0,
      "calculated_weight": 1,
      "purchasing_disabled": false,
      "purchasing_disabled_message": "",
      "image_url": "https://cdn8.bigcommerce.com/s-jrah6gmn/products/174/images/425/leparfaitmedium3_1024x1024_1024x1024__37756__81924.1534344526.560.850.jpg?c=2",
      "cost_price": 0,
      "upc": "",
      "mpn": "",
      "gtin": "",
      "inventory_level": 0,
      "inventory_warning_level": 0,
      "bin_picking_number": "",
      "option_values": []
    }
  ]
} as const;

export const sampleInvalidProductResponse = {
  "id": 174,
  "name": "1L Le Parfait Jar",
  "type": "virtual",
  "sku": "",
  "description": "<p><span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi vel metus ac est egestas porta sed quis erat. Integer id nulla massa. Proin vitae enim nisi. Praesent non dignissim nulla. Nulla mattis id massa ac pharetra. Mauris et nisi in dolor aliquam sodales. Aliquam dui nisl, dictum quis leo sit amet, rutrum volutpat metus. Curabitur libero nunc, interdum ac libero non, tristique porttitor metus. Ut non dignissim lorem, in vestibulum leo. Vivamus sodales quis turpis eget.</span></p>",
  "weight": 1,
  "width": 0,
  "depth": 0,
  "height": 0,
  "price": 7.95,
  "cost_price": 0,
  "retail_price": 10,
  "sale_price": 0,
  "map_price": 0,
  "tax_class_id": 0,
  "product_tax_code": "",
  "calculated_price": 7.95,
  "categories": [
    23,
    21
  ],
  "brand_id": 36,
  "option_set_id": {},
  "option_set_display": "right",
  "inventory_level": 0,
  "inventory_warning_level": 0,
  "inventory_tracking": "none",
  "reviews_rating_sum": 0,
  "reviews_count": 0,
  "total_sold": 7,
  "fixed_cost_shipping_price": 0,
  "is_free_shipping": false,
  "is_visible": true,
  "is_featured": false,
  "related_products": [
    -1
  ],
  "warranty": "",
  "bin_picking_number": "",
  "layout_file": "product.html",
  "upc": "",
  "mpn": "",
  "gtin": "",
  "search_keywords": "jar, glass",
  "availability": "available",
  "availability_description": "",
  "gift_wrapping_options_type": "any",
  "gift_wrapping_options_list": [],
  "sort_order": 0,
  "condition": "New",
  "is_condition_shown": false,
  "order_quantity_minimum": 0,
  "order_quantity_maximum": 0,
  "page_title": "",
  "meta_keywords": [],
  "meta_description": "",
  "date_created": "2018-08-15T14:48:46+00:00",
  "date_modified": "2018-09-05T20:42:07+00:00",
  "view_count": 10,
  "preorder_release_date": "2018-09-05T20:42:07+00:00",
  "preorder_message": "",
  "is_preorder_only": false,
  "is_price_hidden": false,
  "price_hidden_label": "",
  "custom_url": {
    "url": "/all/1l-le-parfait-jar/",
    "is_customized": true
  },
  "base_variant_id": 345,
  "open_graph_type": "product",
  "open_graph_title": "",
  "open_graph_description": "",
  "open_graph_use_meta_description": true,
  "open_graph_use_product_name": true,
  "open_graph_use_image": true,
  "variants": [
    {
      "id": 345,
      "product_id": 174,
      "sku": "",
      "sku_id": {},
      "price": 7.95,
      "calculated_price": 7.95,
      "sale_price": 0,
      "retail_price": 10,
      "map_price": 0,
      "weight": 1,
      "width": 0,
      "height": 0,
      "depth": 0,
      "is_free_shipping": false,
      "fixed_cost_shipping_price": 0,
      "calculated_weight": 1,
      "purchasing_disabled": false,
      "purchasing_disabled_message": "",
      "image_url": "https://cdn8.bigcommerce.com/s-jrah6gmn/products/174/images/425/leparfaitmedium3_1024x1024_1024x1024__37756__81924.1534344526.560.850.jpg?c=2",
      "cost_price": 0,
      "upc": "",
      "mpn": "",
      "gtin": "",
      "inventory_level": 0,
      "inventory_warning_level": 0,
      "bin_picking_number": "",
      "option_values": []
    }
  ]
} as const;

export const sampleInvalidProductResponse2 = {
  "id": 174,
  "type": "physical",
  "sku": "",
  "description": "<p><span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi vel metus ac est egestas porta sed quis erat. Integer id nulla massa. Proin vitae enim nisi. Praesent non dignissim nulla. Nulla mattis id massa ac pharetra. Mauris et nisi in dolor aliquam sodales. Aliquam dui nisl, dictum quis leo sit amet, rutrum volutpat metus. Curabitur libero nunc, interdum ac libero non, tristique porttitor metus. Ut non dignissim lorem, in vestibulum leo. Vivamus sodales quis turpis eget.</span></p>",
  "weight": 1,
  "width": 0,
  "depth": 0,
  "height": 0,
  "cost_price": 0,
  "retail_price": 10,
  "sale_price": 0,
  "map_price": 0,
  "tax_class_id": 0,
  "product_tax_code": "",
  "calculated_price": 7.95,
  "categories": [
    23,
    21
  ],
  "brand_id": 36,
  "option_set_id": {},
  "option_set_display": "right",
  "inventory_level": 0,
  "inventory_warning_level": 0,
  "inventory_tracking": "none",
  "reviews_rating_sum": 0,
  "reviews_count": 0,
  "total_sold": 7,
  "fixed_cost_shipping_price": 0,
  "is_free_shipping": false,
  "is_visible": true,
  "is_featured": false,
  "related_products": [
    -1
  ],
  "warranty": "",
  "bin_picking_number": "",
  "layout_file": "product.html",
  "upc": "",
  "mpn": "",
  "gtin": "",
  "search_keywords": "jar, glass",
  "availability": "available",
  "availability_description": "",
  "gift_wrapping_options_type": "any",
  "gift_wrapping_options_list": [],
  "sort_order": 0,
  "condition": "New",
  "is_condition_shown": false,
  "order_quantity_minimum": 0,
  "order_quantity_maximum": 0,
  "page_title": "",
  "meta_keywords": [],
  "meta_description": "",
  "date_created": "2018-08-15T14:48:46+00:00",
  "date_modified": "2018-09-05T20:42:07+00:00",
  "view_count": 10,
  "preorder_release_date": "2018-09-05T20:42:07+00:00",
  "preorder_message": "",
  "is_preorder_only": false,
  "is_price_hidden": false,
  "price_hidden_label": "",
  "custom_url": {
    "url": "/all/1l-le-parfait-jar/",
    "is_customized": true
  },
  "base_variant_id": 345,
  "open_graph_type": "product",
  "open_graph_title": "",
  "open_graph_description": "",
  "open_graph_use_meta_description": true,
  "open_graph_use_product_name": true,
  "open_graph_use_image": true,
  "variants": [
    {
      "id": 345,
      "product_id": 174,
      "sku": "",
      "sku_id": {},
      "price": 7.95,
      "calculated_price": 7.95,
      "sale_price": 0,
      "retail_price": 10,
      "map_price": 0,
      "weight": 1,
      "width": 0,
      "height": 0,
      "depth": 0,
      "is_free_shipping": false,
      "fixed_cost_shipping_price": 0,
      "calculated_weight": 1,
      "purchasing_disabled": false,
      "purchasing_disabled_message": "",
      "image_url": "https://cdn8.bigcommerce.com/s-jrah6gmn/products/174/images/425/leparfaitmedium3_1024x1024_1024x1024__37756__81924.1534344526.560.850.jpg?c=2",
      "cost_price": 0,
      "upc": "",
      "mpn": "",
      "gtin": "",
      "inventory_level": 0,
      "inventory_warning_level": 0,
      "bin_picking_number": "",
      "option_values": []
    }
  ]
} as const;
